<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { listAgentProfiles } from '../api/agent-config.api'
import type { AgentProfile } from '../api/agent-config.api'
const router = useRouter(); const profiles = ref<AgentProfile[]>([]); const loading = ref(true); const error = ref('')
onMounted(async () => { try { profiles.value = await listAgentProfiles() } catch (cause) { error.value = cause instanceof Error ? cause.message : '配置加载失败' } finally { loading.value = false } })
</script>
<template><main class="agent-config-page"><header class="page-head"><div><p class="eyebrow">AGENT PROFILE CENTER</p><h1>Agent 配置中心</h1><p>管理可版本化的研发 Agent 身份、Prompt、Skills、Tools 与运行约束。</p></div></header><p v-if="loading">正在加载 Agent 配置…</p><p v-else-if="error" class="error">{{ error }}</p><div v-else class="profile-grid"><button v-for="profile in profiles" :key="profile.id" type="button" class="profile-card" @click="router.push({ name:'agent-config-detail', params:{ id: profile.id } })"><span class="profile-card__category">{{ profile.category }}</span><h2>{{ profile.name }}</h2><code>{{ profile.code }}</code><p>{{ profile.description }}</p><footer><span>v{{ profile.latestVersion?.versionNo ?? '—' }} {{ profile.latestVersion?.status ?? '' }}</span><span>{{ profile.latestVersion?.skills?.length ?? 0 }} Skills</span><span>{{ profile.latestVersion?.modelCode || '未配置模型' }}</span></footer></button></div></main></template>
<style scoped>.agent-config-page { max-width:1200px; margin:auto; }.page-head { margin-bottom:24px; }.eyebrow { color:var(--accent-500); font-size:11px; letter-spacing:.14em; }.page-head h1 { margin:4px 0; }.page-head p:last-child { color:var(--text-2); }.profile-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(240px,1fr)); gap:16px; }.profile-card { padding:20px; color:var(--text-1); text-align:left; border:1px solid var(--border-1); border-radius:16px; background:var(--surface-1); cursor:pointer; }.profile-card:hover { border-color:var(--accent-500); }.profile-card h2 { margin:8px 0 4px; }.profile-card code,.profile-card p,.profile-card footer { color:var(--text-2); font-size:12px; }.profile-card p { min-height:40px; line-height:1.6; }.profile-card footer { display:flex; flex-wrap:wrap; gap:8px; padding-top:12px; border-top:1px solid var(--border-1); }.profile-card__category { color:var(--accent-500); font-size:11px; text-transform:uppercase; }.error { color:#c85757; }</style>
