<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { MessagePlugin } from 'tdesign-vue-next'
import { useRoute, useRouter } from 'vue-router'
import { getProjectDocument, listProjects, type Project, type ProjectDocument } from '../api/projects.api'
import { cancelDocumentAgentJob, createDocumentAgentSession, getDocumentAgentEvents, getDocumentAgentJob, listDocumentAgentSessions, resolveDocumentAgentFeishu, searchDocumentAgentFeishu, sendDocumentAgentTurn, type DocumentAgentJob, type DocumentAgentSession, type FeishuDocument } from '../api/document-agent.api'

const projects = ref<Project[]>([]); const documents = ref<ProjectDocument[]>([]); const sessions = ref<DocumentAgentSession[]>([])
const route = useRoute()
const router = useRouter()
const projectKey = ref(''); const profileKey = ref('requirement-analysis/v1'); const mode = ref('NEW'); const title = ref(''); const documentId = ref<number>()
const session = ref<DocumentAgentSession>(); const instruction = ref(''); const output = ref(''); const busy = ref(false); const currentJob = ref<DocumentAgentJob>(); const artifact = ref<ProjectDocument>(); const eventCursor = ref(0); let pollTimer: ReturnType<typeof setTimeout> | undefined
const feishuQuery = ref(''); const feishuResults = ref<FeishuDocument[]>([]); const selectedFeishu = ref<FeishuDocument[]>([])
const selectedProject = computed(() => projects.value.find((v) => v.projectKey === projectKey.value))
async function load() { projects.value = await listProjects(); if (!projectKey.value) projectKey.value = String(route.query.projectKey || projects.value[0]?.projectKey || ''); await refreshProject(); const sessionKey = String(route.query.sessionKey || ''); if (sessionKey) { session.value = sessions.value.find((item) => item.sessionKey === sessionKey); } const jobKey = String(route.query.jobKey || ''); if (jobKey) { currentJob.value = await getDocumentAgentJob(jobKey); void poll(jobKey) } }
async function refreshProject() { if (!projectKey.value) return; const { listProjectDocuments } = await import('../api/projects.api'); documents.value = await listProjectDocuments(projectKey.value); sessions.value = await listDocumentAgentSessions(projectKey.value) }
async function start() { if (!projectKey.value || (mode.value === 'NEW' && !title.value.trim())) return; busy.value = true; try { session.value = await createDocumentAgentSession({ projectKey: projectKey.value, profileKey: profileKey.value, mode: mode.value, documentId: mode.value === 'EXISTING' ? documentId.value : undefined, title: title.value.trim() }); sessions.value = [session.value, ...sessions.value.filter((v) => v.sessionKey !== session.value?.sessionKey)]; await router.replace({ query: { ...route.query, projectKey: projectKey.value, sessionKey: session.value.sessionKey } }); MessagePlugin.success('OpenHands 文档会话已创建') } finally { busy.value = false } }
function parseEvents(stream: string) { for (const block of stream.split(/\n\s*\n/)) { const id = block.match(/^id:\s*(\d+)/m)?.[1]; const type = block.match(/^event:\s*(.+)$/m)?.[1]; const data = block.match(/^data:\s*(.+)$/m)?.[1]; if (id) eventCursor.value = Math.max(eventCursor.value, Number(id)); if (data) { try { const parsed = JSON.parse(data); const text = parsed?.data?.text; if (text) output.value += `${text}\n` } catch { /* non-JSON compatibility event */ } } if (type === 'artifact.saved') output.value += '\n文档草稿已保存。\n' } }
async function poll(jobKey: string) { try { const [job, stream] = await Promise.all([getDocumentAgentJob(jobKey), getDocumentAgentEvents(jobKey, eventCursor.value)]); currentJob.value = job; parseEvents(stream); if (job.status === 'COMPLETED' && job.artifactId && projectKey.value) artifact.value = await getProjectDocument(projectKey.value, job.artifactId); if (!['COMPLETED', 'FAILED', 'CANCELLED'].includes(job.status)) pollTimer = setTimeout(() => void poll(jobKey), 1000) } catch (error) { output.value = `${output.value}\n状态同步失败：${String(error)}`; pollTimer = setTimeout(() => void poll(jobKey), 3000) } }
async function send() { if (!session.value || !instruction.value.trim()) return; busy.value = true; output.value = ''; eventCursor.value = 0; artifact.value = undefined; try { const idempotencyKey = globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`; const job = await sendDocumentAgentTurn(session.value.sessionKey, instruction.value.trim(), { feishuDocuments: selectedFeishu.value.map((v) => ({ docId: v.docId, docType: v.docType, title: v.title })) }, idempotencyKey); currentJob.value = job; instruction.value = ''; await router.replace({ query: { ...route.query, projectKey: projectKey.value, sessionKey: session.value.sessionKey, jobKey: job.jobKey } }); void poll(job.jobKey) } catch (error) { output.value = String(error) } finally { busy.value = false } }
async function cancel() { if (!currentJob.value) return; await cancelDocumentAgentJob(currentJob.value.jobKey); await poll(currentJob.value.jobKey) }
async function searchFeishu() { if (!feishuQuery.value.trim()) return; const data = await searchDocumentAgentFeishu(feishuQuery.value.trim()); const result = data.result ?? data; feishuResults.value = Array.isArray(result) ? result : result.items ?? [] }
async function resolveLink() { const match = feishuQuery.value.match(/(?:docx|docs|sheets|wiki)\/([A-Za-z0-9_-]+)/i); if (!match) return; const doc = await resolveDocumentAgentFeishu(match[1], 'DOCX'); if (doc?.readable !== false) feishuResults.value = [doc, ...feishuResults.value.filter((item) => item.docId !== doc.docId)] }
function toggle(doc: FeishuDocument) { selectedFeishu.value = selectedFeishu.value.some((v) => v.docId === doc.docId) ? selectedFeishu.value.filter((v) => v.docId !== doc.docId) : [...selectedFeishu.value, doc] }
onMounted(() => void load()); onUnmounted(() => { if (pollTimer) clearTimeout(pollTimer) })
</script>
<template>
  <div class="page-shell doc-agent-page"><div class="page-header"><div><h1>文档 Agent</h1><p>独立进入 OpenHands，生成需求、PRD、架构和 UI 文档；不经过 DSH 会话。</p></div></div>
    <section class="card"><div class="form-grid"><label>项目组<select v-model="projectKey" @change="refreshProject"><option v-for="p in projects" :key="p.projectKey" :value="p.projectKey">{{ p.name }}</option></select></label><label>工作流<select v-model="profileKey"><option value="requirement-analysis/v1">需求分析</option><option value="prd-authoring/v1">PRD</option><option value="architecture-design/v1">架构设计</option><option value="ui-design/v1">UI 设计</option></select></label><label>目标<select v-model="mode"><option value="NEW">新建文档</option><option value="EXISTING">继续已有文档</option></select></label><label v-if="mode === 'EXISTING'">文档<select v-model="documentId"><option v-for="d in documents" :key="d.id" :value="d.id">{{ d.title }}</option></select></label><label v-else>文档标题<input v-model="title" placeholder="例如：研发助手 PRD" /></label></div><button class="primary" :disabled="busy || !selectedProject" @click="start">进入 OpenHands</button></section>
    <section class="card"><h2>选择飞书上下文</h2><div class="inline"><input v-model="feishuQuery" placeholder="搜索或粘贴飞书文档链接" @keyup.enter="searchFeishu" /><button @click="searchFeishu">搜索</button><button @click="resolveLink">解析链接</button></div><div class="chips"><button v-for="doc in feishuResults" :key="doc.docId" :class="{selected: selectedFeishu.some((v) => v.docId === doc.docId)}" :disabled="doc.readable === false" @click="toggle(doc)">{{ doc.title || doc.docId }} · {{ doc.docType }}</button></div><p class="muted">已选择 {{ selectedFeishu.length }} 份；SMS 仅保存文档标识，OpenHands 通过 MCP 实时读取。</p></section>
    <section class="card" v-if="session"><h2>{{ session.targetTitle || '文档会话' }}</h2><p class="muted">会话 {{ session.sessionKey }} · {{ session.status }} <span v-if="currentJob">· 任务 {{ currentJob.status }}</span></p><div class="inline"><input v-model="instruction" class="grow" placeholder="告诉 Agent 需要分析或生成什么" @keyup.enter="send" /><button class="primary" :disabled="busy || !!currentJob && !['COMPLETED','FAILED','CANCELLED'].includes(currentJob.status)" @click="send">发送</button><button v-if="currentJob && !['COMPLETED','FAILED','CANCELLED'].includes(currentJob.status)" @click="cancel">取消</button></div><pre v-if="output">{{ output }}</pre><article v-if="artifact" class="artifact-result"><h3>{{ artifact.title }}</h3><p class="muted">{{ artifact.documentType }} · revision {{ artifact.draft?.revisionNo }}</p><div class="markdown-output">{{ artifact.draft?.markdownContent }}</div><a :href="`/projects/${artifact.projectKey}/documents/${artifact.id}`">打开项目文档</a></article></section>
    <section class="card" v-if="sessions.length"><h2>可恢复会话</h2><button v-for="item in sessions" :key="item.sessionKey" class="session" @click="session = item"><span>{{ item.targetTitle || item.profileKey }}</span><small>{{ item.status }} · {{ new Date(item.lastActivityAt).toLocaleString() }}</small></button></section>
  </div>
</template>
<style scoped>
.doc-agent-page{display:grid;gap:16px}.card{background:var(--surface-card,#fff);border:1px solid var(--border-color,#e5e7eb);border-radius:12px;padding:18px}.form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.form-grid label{display:grid;gap:6px;color:#475569;font-size:13px}.form-grid input,.form-grid select,.inline input{border:1px solid #d7dce5;border-radius:8px;padding:9px}.inline{display:flex;gap:8px}.grow{flex:1}.chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.chips button,.session{border:1px solid #d7dce5;background:#fff;border-radius:8px;padding:8px;cursor:pointer}.chips button.selected{background:#eef5ff;border-color:#155eef;color:#155eef}.session{display:flex;justify-content:space-between;width:100%;margin-top:8px}.session small,.muted{color:#64748b}pre{white-space:pre-wrap;background:#f8fafc;padding:12px;border-radius:8px;margin-top:12px}.artifact-result{border-top:1px solid #edf0f5;margin-top:16px;padding-top:12px}.markdown-output{white-space:pre-wrap;background:#f8fafc;border-radius:8px;padding:14px;max-height:480px;overflow:auto;line-height:1.6}@media(max-width:800px){.form-grid{grid-template-columns:1fr 1fr}}
</style>
