<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useAuthStore } from '../stores/auth'
import { getTeamMembers, getTeamTree, grantPlatformMaintainer, grantTeamRole, revokePlatformMaintainer, revokeTeamRole, syncFeishuDirectory, type TeamMember, type TeamView } from '../api/org.api'

const authStore = useAuthStore(); const teams = ref<TeamView[]>([]); const teamKeyword = ref(''); const selected = ref<TeamView | null>(null); const members = ref<TeamMember[]>([]); const activeMember = ref<TeamMember | null>(null); const selectedRole = ref(''); const roleBusy = ref(false); const loading = ref(false); const message = ref('')
const isSuperAdmin = computed(() => authStore.user?.permissions.includes('admin:identity') ?? false); const canManageTeam = computed(() => isSuperAdmin.value || (authStore.user?.permissions.includes('skill:review') ?? false)); const roleOptions = computed(() => isSuperAdmin.value ? [{ key: 'TEAM_ADMIN', label: '团队管理员' }, { key: 'TEAM_MAINTAINER', label: 'Skill 维护员' }, { key: 'PROJECT_MANAGER', label: '项目管理人' }, { key: 'PLATFORM_MAINTAINER', label: '平台级 Skill 维护员' }] : canManageTeam.value ? [{ key: 'TEAM_MAINTAINER', label: 'Skill 维护员' }, { key: 'PROJECT_MANAGER', label: '项目管理人' }] : [])
const filteredTeams = computed(() => { const keyword = teamKeyword.value.trim().toLocaleLowerCase(); return keyword ? teams.value.filter((team) => team.name.toLocaleLowerCase().includes(keyword)) : teams.value })
function roleLabel(role: string) { return ({ TEAM_ADMIN: '团队管理员', TEAM_MAINTAINER: 'Skill 维护员', PROJECT_MANAGER: '项目管理人', PLATFORM_MAINTAINER: '平台级 Skill 维护员' } as Record<string, string>)[role] ?? role }
function roleText(role: TeamMember['roles'][number]) { return role.teamId ? `${roleLabel(role.roleKey)} · 本团队` : roleLabel(role.roleKey) }
async function load() { teams.value = await getTeamTree(); if (teams.value.length) await select(teams.value[0]) }
async function select(team: TeamView) { selected.value = team; members.value = await getTeamMembers(team.id) }
function openMember(member: TeamMember) { activeMember.value = member; selectedRole.value = '' }
async function grantRole() { if (!selected.value || !activeMember.value || !selectedRole.value) return; const userId = activeMember.value.userId; roleBusy.value = true; try { if (selectedRole.value === 'PLATFORM_MAINTAINER') await grantPlatformMaintainer(userId); else await grantTeamRole(selected.value.id, userId, selectedRole.value); message.value = '角色授予成功'; await select(selected.value); activeMember.value = members.value.find((member) => member.userId === userId) ?? null; selectedRole.value = '' } catch (error) { message.value = error instanceof Error ? error.message : '角色授予失败' } finally { roleBusy.value = false } }
async function revokeRole(role: TeamMember['roles'][number]) { if (!selected.value || !activeMember.value || !window.confirm(`确认撤销“${roleLabel(role.roleKey)}”吗？`)) return; const userId = activeMember.value.userId; roleBusy.value = true; try { if (role.roleKey === 'PLATFORM_MAINTAINER') await revokePlatformMaintainer(userId); else await revokeTeamRole(selected.value.id, userId, role.roleKey); message.value = '角色已撤销'; await select(selected.value); activeMember.value = members.value.find((member) => member.userId === userId) ?? null } catch (error) { message.value = error instanceof Error ? error.message : '角色撤销失败' } finally { roleBusy.value = false } }
async function sync() { loading.value = true; message.value = ''; try { const result = await syncFeishuDirectory(); message.value = result.message; } catch (error) { message.value = error instanceof Error ? error.message : '同步任务提交失败' } finally { loading.value = false } }
onMounted(() => void load())
</script>
<template><main class="org-page"><header><div><p class="eyebrow">ORGANIZATION</p><h1>组织与团队权限</h1><p>从飞书同步团队树和成员，为团队分配 Skill 管理角色。</p></div><button class="primary" :disabled="loading" @click="sync">{{ loading ? '任务提交中…' : '同步飞书通讯录' }}</button></header><p v-if="message" class="notice" role="status">{{ message }}</p><section class="org-grid"><aside class="panel"><h2>团队树</h2><input v-model="teamKeyword" class="team-search" type="search" placeholder="搜索团队名称" aria-label="搜索团队名称" /><button v-for="team in filteredTeams" :key="team.id" class="team-row" :class="{ active: selected?.id === team.id }" @click="select(team)">{{ team.name }}<small>{{ team.status }}</small></button><p v-if="!filteredTeams.length" class="muted">未找到匹配团队</p></aside><section class="panel"><h2>{{ selected?.name || '选择团队' }} · 成员</h2><div v-for="member in members" :key="member.userId" class="member-row"><div><strong>{{ member.displayName }}</strong><small>{{ member.username }}</small><div class="role-tags"><span v-for="role in member.roles" :key="`${role.scopeType}-${role.roleKey}-${role.teamId}`" class="role-tag">{{ roleText(role) }}</span><span v-if="!member.roles.length" class="muted">暂无特殊角色</span></div></div><div class="member-actions"><span>{{ member.membershipType }}</span><button v-if="canManageTeam" class="link-button" @click="openMember(member)">管理权限</button></div></div><p v-if="selected && !members.length" class="muted">该团队暂无成员</p></section></section></main><div v-if="activeMember" class="modal-mask" @click.self="activeMember = null"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="role-dialog-title"><button class="modal-close" aria-label="关闭" @click="activeMember = null">×</button><p class="eyebrow">ROLE MANAGEMENT</p><h2 id="role-dialog-title">{{ activeMember.displayName }} 的权限</h2><p class="muted">{{ activeMember.username }}</p><h3>当前角色</h3><div v-if="activeMember.roles.length" class="current-roles"><div v-for="role in activeMember.roles" :key="`${role.scopeType}-${role.roleKey}-${role.teamId}`" class="current-role"><span>{{ roleText(role) }}</span><button class="link-button danger" :disabled="roleBusy" @click="revokeRole(role)">撤销</button></div></div><p v-else class="muted">暂无特殊角色</p><div v-if="roleOptions.length" class="grant-row"><select v-model="selectedRole" aria-label="选择要授予的角色"><option value="">选择要授予的角色</option><option v-for="role in roleOptions" :key="role.key" :value="role.key">{{ role.label }}</option></select><button class="primary" :disabled="roleBusy || !selectedRole" @click="grantRole">{{ roleBusy ? '处理中…' : '授予角色' }}</button></div></section></div></template>
<style scoped>
.role-tags{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.role-tag{background:#fff1e0;color:#b34a00;border-radius:999px;padding:3px 8px;font-size:12px}.member-actions{display:flex;align-items:center;gap:14px;white-space:nowrap}.link-button{border:0;background:transparent;color:#b34a00;cursor:pointer}.link-button.danger{color:#c0392b}.modal-mask{position:fixed;inset:0;background:rgba(15,23,42,.36);display:grid;place-items:center;padding:20px;z-index:20}.modal{position:relative;background:#fff;border-radius:18px;padding:28px;max-width:520px;width:100%;box-shadow:0 20px 60px rgba(15,23,42,.2)}.modal-close{position:absolute;right:18px;top:14px;border:0;background:transparent;font-size:26px;color:#64748b;cursor:pointer}.modal h2{margin:8px 0 4px}.modal h3{margin:24px 0 10px}.current-roles{display:grid;gap:8px}.current-role{display:flex;justify-content:space-between;align-items:center;background:#fbf6f0;border-radius:10px;padding:10px 12px}.grant-row{display:flex;gap:10px;margin-top:22px}.grant-row select{flex:1;border:1px solid #dfcfb8;border-radius:8px;padding:10px;background:#fff}
.org-page{padding:40px;max-width:1180px;margin:auto}.org-page header{display:flex;justify-content:space-between;align-items:flex-start;gap:24px}.eyebrow{letter-spacing:.16em;font-size:12px;color:#7b8794}h1{margin:8px 0;font-size:34px}.org-grid{display:grid;grid-template-columns:320px 1fr;gap:20px;margin-top:28px}.panel{background:#fff;border:1px solid #ece1d2;border-radius:18px;padding:22px;min-height:260px}.team-row{display:flex;width:100%;justify-content:space-between;border:0;background:transparent;padding:12px;border-radius:10px;text-align:left;cursor:pointer}.team-row.active{background:#fff1e0;color:#b34a00}.team-row small,.member-row small{display:block;color:#8a94a3;font-size:12px}.member-row{display:flex;justify-content:space-between;padding:14px 0;border-bottom:1px solid #f6efe5}.primary{background:#b34a00;color:#fff;border:0;border-radius:10px;padding:11px 16px;cursor:pointer}.primary:disabled{opacity:.6}.notice{background:#eef7ee;padding:12px;border-radius:10px}.muted{color:#8a94a3}@media(max-width:760px){.org-page{padding:20px}.org-page header{display:block}.org-grid{grid-template-columns:1fr}}
.team-search{box-sizing:border-box;width:100%;margin:8px 0 10px;padding:9px 10px;border:1px solid #dfcfb8;border-radius:8px;color:#1e293b;background:#fff;font:inherit;font-size:13px;outline:none}.team-search:focus{border-color:#e86600}
</style>
