<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, watch } from 'vue'; import { useRoute } from 'vue-router'; import { sendIntervention } from '../api/workflow.api'; import WorkflowGraph from '../components/workflow/WorkflowGraph.vue'; import AgentInterventionChat from '../features/intervention/AgentInterventionChat.vue'; import { useProjectWorkspaceStore } from '../stores/projectWorkspace'; import { useRuntimeEventStore } from '../stores/runtimeEvent'; import type { InterventionType, WorkflowStage } from '../types/workflow'
const route=useRoute(); const workspace=useProjectWorkspaceStore(); const runtime=useRuntimeEventStore(); const runId=computed(()=>String(route.params.runId || '')); const selectedStage=computed(()=>workspace.stagesById[workspace.selectedStageId || '']); const running=computed(()=>['RUNNING','PROVISIONING'].includes(workspace.workflowRun?.status || ''))
onMounted(async()=>{ if (!runId.value) return; await workspace.load(runId.value); if(workspace.workflowRun) runtime.connect(String(workspace.workflowRun.id)) }); watch(()=>runtime.events.length,()=>{ const e=runtime.events.at(-1); if(e){ workspace.applyEvent(e); }}); onBeforeUnmount(()=>runtime.close())
async function intervention(type: InterventionType, content?: string) { await sendIntervention(String(workspace.workflowRun?.id || runId.value),type,content) }
function choose(stage: WorkflowStage) { workspace.selectedStageId=stage.id }
</script>
<template><main class="workspace"><header class="workspace-head"><div><p class="eyebrow">PROJECT WORKSPACE</p><h1>Agent 驱动项目工作台</h1><p v-if="runId">Run {{ workspace.workflowRun?.id || runId }} · {{ workspace.workflowRun?.status || '加载中' }}</p><p v-else>尚未启动 Agent Workflow Run</p></div><div class="live" :class="{online:runtime.connected}">{{ runtime.connected ? '实时连接中' : runtime.reconnecting ? '正在重连…' : '未连接' }}</div></header><p v-if="workspace.error" class="error">{{ workspace.error }}</p><section v-if="!runId" class="panel start-state"><h2>等待启动</h2><p class="muted">请从项目页点击“启动 Agent 工作流”，系统会创建运行实例后进入本工作台。</p></section><template v-else><WorkflowGraph :stages="workspace.stages" :selected-id="workspace.selectedStageId" @select="choose"/><div class="workspace-grid"><section class="panel"><header><h2>{{ selectedStage?.name || '选择阶段' }}</h2><span>{{ selectedStage?.status || '' }}</span></header><div v-if="selectedStage?.agents?.length" class="agents"><div v-for="agent in selectedStage.agents" :key="agent.id" class="agent-node"><strong>{{ agent.name }}</strong><small>{{ agent.status }} · {{ agent.profileCode || 'Agent' }}</small></div></div><p v-else class="muted">选择阶段查看 Agent DAG、产物与执行参数。</p></section><section class="panel timeline"><h2>执行轨迹</h2><div v-for="(event,index) in runtime.events.slice(-20).reverse()" :key="event.id || `${event.type}-${index}`"><time>{{ event.createdAt || '' }}</time><strong>{{ event.type }}</strong><span>{{ String(event.data.message || event.data.stageName || '') }}</span></div><p v-if="!runtime.events.length" class="muted">等待运行事件…</p></section></div><AgentInterventionChat :running="running" @submit="intervention" @action="intervention"/></template></main></template>
<style scoped>.workspace { max-width:1240px; margin:auto; }.workspace-head { display:flex; justify-content:space-between; align-items:start; margin-bottom:22px; }.workspace-head p:last-child,.muted { color:var(--text-2); }.eyebrow { color:var(--accent-500); font-size:11px; letter-spacing:.14em; }.live { padding:7px 10px; color:var(--text-2); border-radius:99px; background:var(--surface-2); }.live.online { color:#258b5f; }.workspace-grid { display:grid; grid-template-columns:1fr 1fr; gap:16px; margin:16px 0; }.panel { padding:20px; border:1px solid var(--border-1); border-radius:16px; background:var(--surface-1); }.panel header { display:flex; justify-content:space-between; align-items:center; }.panel h2 { margin-top:0; }.agents { display:grid; gap:9px; }.agent-node { display:grid; gap:4px; padding:12px; border-left:3px solid var(--accent-500); background:var(--surface-2); }.agent-node small,.timeline time,.timeline span { color:var(--text-2); font-size:12px; }.timeline > div { display:grid; grid-template-columns:130px 1fr; gap:6px; padding:9px 0; border-bottom:1px solid var(--border-1); }.timeline span { grid-column:2; }.error { color:#c85757; }@media(max-width:700px){.workspace-grid{grid-template-columns:1fr}.workspace-head{display:block}.live{display:inline-block;margin-top:10px}}
</style>
