<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { designAcceptWorkflowRun, sendIntervention } from '../api/workflow.api'
import WorkflowGraph from '../components/workflow/WorkflowGraph.vue'
import AgentInterventionChat from '../features/intervention/AgentInterventionChat.vue'
import { useProjectWorkspaceStore } from '../stores/projectWorkspace'
import { useRuntimeEventStore } from '../stores/runtimeEvent'
import type { InterventionTarget, InterventionType, WorkflowStage } from '../types/workflow'

const route = useRoute(); const workspace = useProjectWorkspaceStore(); const runtime = useRuntimeEventStore(); const runId = computed(() => String(route.params.runId || '')); const selectedStage = computed(() => workspace.stagesById[workspace.selectedStageId || '']); const requirement = computed(() => workspace.stages.find((stage) => stage.key === 'REQUIREMENT' || stage.key === 'requirement' || stage.name.includes('需求'))); const running = computed(() => ['RUNNING', 'PROVISIONING'].includes(workspace.workflowRun?.status || '')); const acceptanceComment = ref(''); const accepting = ref(false)
const requirementAgents = computed(() => requirement.value?.agents ?? [])
onMounted(async () => { if (!runId.value) return; await workspace.load(runId.value); if (workspace.workflowRun) runtime.connect(String(workspace.workflowRun.id)) })
watch(() => runtime.events.length, () => { const event = runtime.events.at(-1); if (event) workspace.applyEvent(event) })
onBeforeUnmount(() => runtime.close())
async function intervention(type: InterventionType, content?: string, target?: InterventionTarget) { await sendIntervention(String(workspace.workflowRun?.id || runId.value), type, content, target) }
function choose(stage: WorkflowStage) { workspace.selectedStageId = stage.id }
async function acceptance(decision: 'ACCEPT' | 'REWORK') { if (!workspace.workflowRun || accepting.value) return; accepting.value = true; try { await designAcceptWorkflowRun(String(workspace.workflowRun.id), decision, 'REQUIREMENT', acceptanceComment.value) } finally { accepting.value = false } }
</script>
<template>
  <main class="workspace">
    <header class="workspace-head"><div><p class="eyebrow">PROJECT WORKSPACE</p><h1>Agent 驱动项目工作台</h1><p v-if="runId">Run {{ workspace.workflowRun?.id || runId }} · {{ workspace.workflowRun?.status || '加载中' }}</p><p v-else>尚未启动 Agent Workflow Run</p></div><div class="live" :class="{online:runtime.connected}">{{ runtime.connected ? '实时连接中' : runtime.reconnecting ? '正在重连…' : '未连接' }}</div></header>
    <p v-if="workspace.error" class="error">{{ workspace.error }}</p><section v-if="!runId" class="panel start-state"><h2>等待启动</h2><p class="muted">请从项目页启动 Agent Workflow。</p></section>
    <template v-else>
      <WorkflowGraph :stages="workspace.stages" :selected-id="workspace.selectedStageId" @select="choose" />
      <section class="panel requirement-team" data-testid="agent-team"><header><h2>Requirement Agent Team</h2><span>{{ requirement?.status || 'PENDING' }}</span></header><div class="team-grid"><article v-for="agent in requirementAgents" :key="agent.id" class="agent-node"><strong>{{ agent.name }}</strong><small>{{ agent.key }} · {{ agent.status }}</small></article><article v-if="!requirementAgents.length" class="agent-node"><strong>Clarifier · Writer · Reviewer</strong><small>等待后端 Agent DAG 数据</small></article></div><p v-if="requirement?.status === 'HUMAN_REQUIRED'" class="human-required">HUMAN_REQUIRED：需要人员处理后才能继续。</p></section>
      <div class="workspace-grid"><section class="panel"><header><h2>{{ selectedStage?.name || '选择阶段' }}</h2><span>{{ selectedStage?.status || '' }}</span></header><div v-if="selectedStage?.artifacts?.length" class="revisions"><h3>Document Revision</h3><article v-for="artifact in selectedStage.artifacts" :key="artifact.id" data-testid="document-revision"><strong>{{ artifact.name }}</strong><span>Revision {{ artifact.revision ?? artifact.revisionId ?? '—' }}</span><p v-for="issue in artifact.reviewIssues ?? []" :key="issue" class="issue">review issues: {{ issue }}</p></article></div><p v-else class="muted">选择阶段查看 Agent DAG、产物与 Revision。</p></section><section class="panel timeline" data-testid="timeline"><h2>执行轨迹</h2><div v-for="(event,index) in runtime.events.slice(-30).reverse()" :key="event.id || `${event.type}-${index}`"><time>{{ event.createdAt || '' }}</time><strong>{{ event.type }}</strong><span>{{ String(event.data.message || event.data.stageName || event.data.agentName || '') }}</span></div><p v-if="!runtime.events.length" class="muted">等待运行事件…</p></section></div>
      <section v-if="workspace.workflowRun?.status === 'WAITING_DESIGN_ACCEPTANCE' || requirement?.status === 'HUMAN_REQUIRED'" class="panel acceptance" data-testid="final-acceptance"><h2>Requirement 完成审批</h2><p class="muted">真实项目成员审批需求阶段后，流程才会进入设计阶段。</p><textarea v-model="acceptanceComment" rows="3" placeholder="审批备注（可选）" data-testid="acceptance-comment"/><div><button type="button" class="primary" :disabled="accepting" @click="acceptance('ACCEPT')">通过 Requirement</button><button type="button" class="danger" :disabled="accepting" @click="acceptance('REWORK')">退回 Requirement</button></div></section>
      <AgentInterventionChat :running="running" :target="{ targetStageKey: selectedStage?.key }" @submit="intervention" @action="(type, target) => intervention(type, undefined, target)" />
    </template>
  </main>
</template>
<style scoped>.workspace{max-width:1240px;margin:auto}.workspace-head{display:flex;justify-content:space-between;align-items:start;margin-bottom:22px}.workspace-head p:last-child,.muted{color:var(--text-2)}.eyebrow{color:var(--accent-500);font-size:11px;letter-spacing:.14em}.live{padding:7px 10px;color:var(--text-2);border-radius:99px;background:var(--surface-2)}.live.online{color:#258b5f}.panel{padding:20px;margin:16px 0;border:1px solid var(--border-1);border-radius:16px;background:var(--surface-1)}.panel header{display:flex;justify-content:space-between;align-items:center}.team-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.agent-node{display:grid;gap:4px;padding:12px;border-left:3px solid var(--accent-500);background:var(--surface-2)}.agent-node small,.timeline time,.timeline span,.revisions span{color:var(--text-2);font-size:12px}.workspace-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.timeline>div{display:grid;grid-template-columns:130px 1fr;gap:6px;padding:9px 0;border-bottom:1px solid var(--border-1)}.timeline span{grid-column:2}.revisions article{display:grid;gap:5px;padding:12px;margin-top:8px;border:1px solid var(--border-1);border-radius:8px}.issue,.human-required,.error{color:#c85757}.acceptance textarea{box-sizing:border-box;width:100%;margin:10px 0;padding:10px;color:var(--text-1);background:var(--surface-2);border:1px solid var(--border-1);border-radius:8px}.acceptance button{padding:9px 13px;margin-right:8px;border:1px solid var(--border-1);border-radius:8px}.primary{color:#fff;background:var(--accent-600)}.danger{color:#fff;background:#b94e55}@media(max-width:700px){.workspace-grid,.team-grid{grid-template-columns:1fr}.workspace-head{display:block}}
</style>
