<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { listAgentLibrary, listTeamPresets, getProjectAgentNode, saveProjectAgentNodeDraft, getProjectAgentContexts, saveProjectAgentContexts, reviseProjectAgentConfiguration } from '../api/agent-library.api'
import { getCurrentWorkflowRun, startWorkflowRun } from '../api/workflow.api'
import { getWikiDocuments } from '../api/wiki.api'
import { searchDocumentAgentFeishu } from '../api/document-agent.api'
import type { AgentLibraryProfile, AgentTeamPreset, ProjectAgentContext, ProjectAgentContexts, ProjectAgentNodeDraft } from '../types/agent-library'
import { useProjectSetupStore } from '../stores/projectSetup'

const route = useRoute(); const router = useRouter(); const setup = useProjectSetupStore(); const projectKey = String(route.params.projectKey)
const profiles = ref<AgentLibraryProfile[]>([]); const presets = ref<AgentTeamPreset[]>([]); const source = ref<'SYSTEM_PRESET'|'PROJECT_COPY'|'CUSTOM'>('SYSTEM_PRESET'); const selectedPreset = ref<string|number|null>(null); const sourceProjectKey = ref(''); const selectedDraft = ref<ProjectAgentNodeDraft|null>(null); const contexts = ref<ProjectAgentContexts>({ platformWiki: [], feishu: [] }); const initialRequest = ref(''); const wikiQuery = ref(''); const feishuQuery = ref(''); const contextTab = ref<'PLATFORM_WIKI'|'FEISHU'>('PLATFORM_WIKI'); const message = ref(''); const busy = ref(false); const saving = ref(false); const resolvingEntry = ref(true)
const selectedNode = computed(() => setup.configuration?.nodes.find(n => `${n.stageKey}/${n.nodeKey}` === setup.selectedNodeKey)); const ready = computed(() => setup.configuration?.status === 'READY'); const draftMode = computed(() => setup.configuration?.status === 'DRAFT')
const runtimeConfigText = computed({ get: () => typeof selectedDraft.value?.runtimeConfigJson === 'string' ? selectedDraft.value.runtimeConfigJson : JSON.stringify(selectedDraft.value?.runtimeConfigJson ?? {}, null, 2), set: value => { if (selectedDraft.value) selectedDraft.value.runtimeConfigJson = value } })
const skillsText = computed({ get: () => JSON.stringify(selectedDraft.value?.skills ?? [], null, 2), set: value => { if (selectedDraft.value) { try { selectedDraft.value.skills = JSON.parse(value) } catch (error) { void error } } } })
async function loadNode() { if (!selectedNode.value) return; try { selectedDraft.value = await getProjectAgentNode(projectKey, selectedNode.value.stageKey, selectedNode.value.nodeKey) } catch (e) { message.value = e instanceof Error ? e.message : 'Agent 草稿加载失败' } }
const wikiResults = ref<ProjectAgentContext[]>([]); const feishuResults = ref<ProjectAgentContext[]>([])
async function loadAll() { await Promise.allSettled([setup.load(projectKey), setup.loadReusable(projectKey), listAgentLibrary().then(v => profiles.value = v), listTeamPresets().then(v => { presets.value = v; selectedPreset.value = v.find(x => x.isDefault)?.versionId ?? v[0]?.versionId ?? null }), getProjectAgentContexts(projectKey).then(v => contexts.value = v)]); const firstNode = setup.configuration?.nodes?.[0]; if (firstNode) { setup.selectedNodeKey = `${firstNode.stageKey}/${firstNode.nodeKey}`; await loadNode() } }
async function resolveEntry() { try { const run = await getCurrentWorkflowRun(projectKey); await router.replace({ name: 'project-workspace', params: { projectId: projectKey, runId: String(run.id) } }) } catch (error) { const status = (error as any)?.response?.status; const code = (error as any)?.response?.data?.code; if (status === 404 || code === 'WORKFLOW_RUN_NOT_FOUND') { resolvingEntry.value = false; await loadAll() } else { resolvingEntry.value = false; message.value = (error as any)?.response?.data?.message || '工作流状态查询失败，请稍后重试' } } }
onMounted(resolveEntry)
async function applySource() { busy.value = true; try { if (source.value === 'SYSTEM_PRESET' && selectedPreset.value != null) await setup.usePreset(projectKey, selectedPreset.value); else if (source.value === 'PROJECT_COPY' && sourceProjectKey.value) await setup.copyFrom(projectKey, sourceProjectKey.value); setup.selectedNodeKey = setup.configuration?.nodes[0] ? `${setup.configuration.nodes[0].stageKey}/${setup.configuration.nodes[0].nodeKey}` : ''; await loadNode() } catch (e) { message.value = e instanceof Error ? e.message : '配置来源应用失败' } finally { busy.value = false } }
async function saveNode() { if (!selectedNode.value || !selectedDraft.value) return; saving.value = true; try { await saveProjectAgentNodeDraft(projectKey, selectedNode.value.stageKey, selectedNode.value.nodeKey, { systemPrompt: selectedDraft.value.systemPrompt, modelCode: selectedDraft.value.modelCode, temperature: selectedDraft.value.temperature, maxIterationPerRun: selectedDraft.value.maxIterationPerRun, timeoutSeconds: selectedDraft.value.timeoutSeconds, outputSchemaJson: typeof selectedDraft.value.outputSchemaJson === 'string' ? selectedDraft.value.outputSchemaJson : JSON.stringify(selectedDraft.value.outputSchemaJson ?? {}), runtimeConfigJson: typeof selectedDraft.value.runtimeConfigJson === 'string' ? selectedDraft.value.runtimeConfigJson : JSON.stringify(selectedDraft.value.runtimeConfigJson ?? {}), skills: selectedDraft.value.skills }); message.value = '当前 Node 草稿已保存' } catch (e) { message.value = e instanceof Error ? e.message : '草稿保存失败' } finally { saving.value = false } }
async function saveContexts() { try { contexts.value = await saveProjectAgentContexts(projectKey, contexts.value); message.value = '启动上下文已保存' } catch (e) { message.value = e instanceof Error ? e.message : '上下文保存失败' } }
async function revise() { try { setup.configuration = await reviseProjectAgentConfiguration(projectKey); message.value = '已创建可编辑配置修订' } catch (e) { message.value = e instanceof Error ? e.message : '创建修订失败' } }
async function validate() { try { await setup.validate(projectKey) } catch (e) { message.value = e instanceof Error ? e.message : '配置校验失败' } }
async function confirm() { try { await setup.confirm(projectKey) } catch (e) { message.value = e instanceof Error ? e.message : '配置确认失败' } }
async function start() { if (!initialRequest.value.trim() || !ready.value) return; try { const run = await startWorkflowRun(projectKey, { initialRequest: initialRequest.value.trim() }); await router.push({ name: 'project-workspace', params: { projectId: projectKey, runId: String(run.id) } }) } catch (e) { message.value = e instanceof Error ? e.message : 'Workflow 启动失败' } }
function remove(kind: 'platformWiki'|'feishu', item: ProjectAgentContext) { contexts.value[kind] = contexts.value[kind].filter(x => String(x.id) !== String(item.id)) }
async function searchContext() { try { if (contextTab.value === 'PLATFORM_WIKI') { const page = await getWikiDocuments({ keyword: wikiQuery.value.trim() || undefined, page: 0, size: 10 }); wikiResults.value = page.items.map(x => ({ kind: 'PLATFORM_WIKI', id: x.id, title: x.title, revisionNo: x.revisionNo })) } else { const raw = await searchDocumentAgentFeishu(feishuQuery.value.trim()); const data = Array.isArray(raw) ? raw : (raw as any).result ?? raw; const items = (data as any).files ?? (data as any).items ?? (data as any).docs ?? []; feishuResults.value = items.filter((x: any) => x.readable !== false).map((x: any) => ({ kind: 'FEISHU', id: x.docId, title: x.title || x.docId, docType: x.docType, url: x.open_url })) } } catch (e) { message.value = e instanceof Error ? e.message : '上下文搜索失败' } }
function addContext(item: ProjectAgentContext) { const key = item.kind === 'PLATFORM_WIKI' ? 'platformWiki' : 'feishu'; if (contexts.value[key].some(x => String(x.id) === String(item.id)) || contexts.value[key].length >= 10) return; contexts.value[key] = [...contexts.value[key], item] }
</script>
<template>
  <main v-if="resolvingEntry" class="setup-workbench"><section class="panel muted">正在检查项目工作流…</section></main>
  <main v-else class="setup-workbench"><header class="hero"><div><p class="eyebrow">PROJECT AGENT SETUP</p><h1>项目 Agent 配置</h1><p class="muted">先复制为项目私有草稿，再按 Node 调整 Prompt、Skill 与启动资料。</p></div><div class="status-stack"><span class="status">{{ setup.configuration?.status || 'DRAFT' }}</span><button v-if="!draftMode" @click="revise">创建配置修订</button></div></header><p v-if="message || setup.error" class="notice">{{ message || setup.error }}</p>
    <section class="source panel"><div><span class="step">01</span><h2>配置来源</h2><p class="muted">来源应用后，每个 Node 都是当前项目独立副本。</p></div><div class="tabs"><button :class="{active:source==='SYSTEM_PRESET'}" @click="source='SYSTEM_PRESET'">系统推荐</button><button :class="{active:source==='PROJECT_COPY'}" @click="source='PROJECT_COPY'">历史项目</button><button :class="{active:source==='CUSTOM'}" @click="source='CUSTOM'">自定义</button></div><div v-if="source==='SYSTEM_PRESET'" class="inline"><select v-model="selectedPreset"><option v-for="p in presets" :key="String(p.versionId)" :value="p.versionId">{{ p.name }} v{{ p.versionNo }}</option></select><button @click="applySource">应用方案</button></div><div v-else-if="source==='PROJECT_COPY'" class="inline"><select v-model="sourceProjectKey"><option value="">选择历史项目</option><option v-for="p in setup.reusableProjects" :key="p.projectKey" :value="p.projectKey">{{ p.name }} · {{ p.status }}</option></select><button @click="applySource">复制为草稿</button></div><p v-else class="muted">选择下方 Node 后编辑项目私有 Agent。</p></section>
    <section class="editor panel"><div class="section-head"><div><span class="step">02</span><h2>Agent 团队</h2></div><span class="muted">{{ setup.configuration?.nodes.length || 0 }} Nodes</span></div><div class="editor-grid"><nav class="node-list"><button v-for="n in setup.configuration?.nodes || []" :key="`${n.stageKey}/${n.nodeKey}`" :class="{selected:setup.selectedNodeKey===`${n.stageKey}/${n.nodeKey}`}" @click="setup.selectedNodeKey=`${n.stageKey}/${n.nodeKey}`; loadNode()"><strong>{{ n.nodeName || n.nodeKey }}</strong><small>{{ n.stageKey }} · {{ n.agentProfileCode }}</small></button></nav><article v-if="selectedDraft" class="inspector"><div class="section-head"><div><h3>{{ selectedDraft.nodeName || selectedDraft.nodeKey }}</h3><p class="muted">项目私有 Draft · 来源版本 {{ selectedDraft.sourceAgentProfileVersionId || '—' }}</p></div><button :disabled="saving || !draftMode" @click="saveNode">{{ saving ? '保存中…' : '保存此 Agent' }}</button></div><label>System Prompt<textarea v-model="selectedDraft.systemPrompt" rows="9" :disabled="!draftMode" /></label><div class="form-grid"><label>Model<input v-model="selectedDraft.modelCode" :disabled="!draftMode" /></label><label>Temperature<input v-model.number="selectedDraft.temperature" type="number" step="0.1" :disabled="!draftMode" /></label><label>Max Iteration<input v-model.number="selectedDraft.maxIterationPerRun" type="number" :disabled="!draftMode" /></label><label>Timeout（秒）<input v-model.number="selectedDraft.timeoutSeconds" type="number" :disabled="!draftMode" /></label></div><details><summary>Skills / Runtime 高级配置</summary><label>Skill bindings JSON<textarea v-model="skillsText" rows="7" :disabled="!draftMode" /></label><label>Runtime Config JSON<textarea v-model="runtimeConfigText" rows="5" :disabled="!draftMode" /></label></details></article><p v-else class="empty">选择一个 Node 开始编辑</p></div></section>
    <section class="context panel"><div class="section-head"><div><span class="step">03</span><h2>启动上下文</h2><p class="muted">整个 Run 共享；平台 Wiki 启动时固定版本，飞书固定文档身份。</p></div><button :disabled="!draftMode" @click="saveContexts">保存上下文</button></div><div class="context-tabs"><button :class="{active:contextTab==='PLATFORM_WIKI'}" @click="contextTab='PLATFORM_WIKI'">平台 Wiki <b>{{ contexts.platformWiki.length }}/10</b></button><button :class="{active:contextTab==='FEISHU'}" @click="contextTab='FEISHU'">飞书 <b>{{ contexts.feishu.length }}/10</b></button></div><div class="context-search"><input v-if="contextTab==='PLATFORM_WIKI'" v-model="wikiQuery" placeholder="搜索平台 Wiki" @keyup.enter="searchContext" /><input v-else v-model="feishuQuery" placeholder="搜索或粘贴飞书文档" @keyup.enter="searchContext" /><button @click="searchContext">搜索</button></div><div class="results"><button v-for="item in contextTab==='PLATFORM_WIKI'?wikiResults:feishuResults" :key="`${item.kind}-${item.id}`" @click="addContext(item)"><span>{{ item.title }}</span><small>{{ item.revisionNo ? `v${item.revisionNo}` : item.docType }}</small></button></div><div class="selected"><span v-for="item in contexts[contextTab==='PLATFORM_WIKI'?'platformWiki':'feishu']" :key="String(item.id)" class="tag">{{ item.title }} <button @click="remove(contextTab==='PLATFORM_WIKI'?'platformWiki':'feishu',item)">×</button></span><p v-if="!contexts[contextTab==='PLATFORM_WIKI'?'platformWiki':'feishu'].length" class="muted">尚未选择资料</p></div></section>
    <section class="footer panel"><div><span class="step">04</span><h2>校验并启动</h2><p class="muted">确认后项目 Agent 草稿冻结；启动时生成上下文快照。</p></div><div class="actions"><button @click="validate">校验配置</button><button v-if="setup.configuration?.status==='READY'" class="primary" :disabled="!initialRequest.trim()" @click="start">启动 Workflow</button><button v-else class="primary" @click="confirm">确认配置</button></div><textarea v-if="setup.configuration?.status==='READY'" v-model="initialRequest" data-testid="initial-request" rows="3" placeholder="输入本次研发需求" /></section>
  </main>
</template>
<style scoped>
.setup-workbench{max-width:1240px;margin:auto;padding-bottom:70px}.hero,.section-head,.inline,.actions,.context-search{display:flex;align-items:center;justify-content:space-between;gap:14px}.hero{align-items:flex-start}.eyebrow,.step{color:var(--accent-500);font-size:11px;letter-spacing:.14em}.muted{color:var(--text-2)}.status-stack{display:flex;gap:8px;align-items:center}.status,.tag{padding:7px 10px;border-radius:999px;background:var(--surface-2)}.panel{margin:16px 0;padding:22px;border:1px solid var(--border-1);border-radius:14px;background:var(--surface-1)}h2,h3{margin:4px 0}.tabs,.context-tabs{display:flex;gap:8px;margin:14px 0}.tabs button,.context-tabs button,.panel button{padding:9px 13px;border:1px solid var(--border-1);border-radius:8px;background:var(--surface-2);color:var(--text-1)}.tabs .active,.context-tabs .active,.primary{color:#fff;background:var(--accent-600);border-color:var(--accent-600)}.inline{justify-content:flex-start}.inline select,.context-search input,.panel input,.panel textarea{padding:10px;border:1px solid var(--border-1);border-radius:8px;background:var(--surface-2);color:var(--text-1);font:inherit}.editor-grid{display:grid;grid-template-columns:280px 1fr;gap:18px}.node-list{display:grid;align-content:start;gap:8px}.node-list button{display:grid;text-align:left;gap:5px}.node-list button.selected{border-color:var(--accent-500);box-shadow:inset 3px 0 var(--accent-500)}.node-list small{color:var(--text-2)}.inspector{display:grid;gap:14px}.inspector label{display:grid;gap:6px;color:var(--text-2)}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.json-preview{max-height:180px;overflow:auto;white-space:pre-wrap;color:var(--text-2)}.context-search{justify-content:flex-start}.context-search input{flex:1}.selected,.results{display:flex;flex-wrap:wrap;gap:7px;min-height:44px;align-items:center}.results{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));margin-top:10px}.results button{display:flex;justify-content:space-between;text-align:left}.results small{color:var(--text-2)}.tag{display:inline-flex;gap:6px}.tag button{border:0;padding:0;background:transparent}.empty{padding:40px;color:var(--text-2)}.footer{position:sticky;bottom:12px;z-index:2}.footer textarea{width:100%;margin-top:14px;box-sizing:border-box}@media(max-width:760px){.hero,.section-head{display:block}.editor-grid{grid-template-columns:1fr}.form-grid,.results{grid-template-columns:1fr}.status-stack{margin-top:12px}.footer{position:static}}
</style>
