import { http } from './http'
import type { AgentLibraryProfile, AgentTeamPreset, ProjectAgentConfiguration, ProjectConfigValidation, ReusableProject, ProjectAgentNodeDraft, ProjectAgentContexts } from '../types/agent-library'

export async function listAgentLibrary(params?: { sourceType?: string; category?: string }) { return (await http.get<AgentLibraryProfile[]>('/agent-profiles', { params })).data }
export async function forkAgent(code: string, input: { newCode: string; newName: string; versionNo?: number }) { return (await http.post<AgentLibraryProfile>(`/agent-profiles/${encodeURIComponent(code)}:fork`, input)).data }
type PresetEnvelope = AgentTeamPreset[] | { items?: AgentTeamPreset[]; presets?: AgentTeamPreset[]; data?: AgentTeamPreset[] }
function normalizePreset(raw: AgentTeamPreset): AgentTeamPreset {
  const candidate = raw as AgentTeamPreset & { id?: string | number; latestVersion?: AgentTeamPreset & { id?: string | number }; latestPublishedVersion?: AgentTeamPreset & { id?: string | number } }
  const version = candidate.latestPublishedVersion ?? candidate.latestVersion
  return { ...raw, versionId: raw.versionId ?? version?.versionId ?? version?.id, versionNo: raw.versionNo ?? version?.versionNo, bindings: raw.bindings ?? version?.bindings ?? [] }
}
export async function listTeamPresets() { const { data } = await http.get<PresetEnvelope>('/agent-team-presets'); const items = Array.isArray(data) ? data : (data.items ?? data.presets ?? data.data ?? []); return items.map(normalizePreset) }
export async function getProjectAgentConfiguration(projectKey: string) { return (await http.get<ProjectAgentConfiguration>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration`)).data }
export async function applyPreset(projectKey: string, presetVersionId: string | number) { return (await http.post<ProjectAgentConfiguration>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration:apply-preset`, { presetVersionId })).data }
export async function copyProjectConfiguration(projectKey: string, sourceProjectKey: string) { return (await http.post<ProjectAgentConfiguration>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration:copy-from-project`, { sourceProjectKey, versionStrategy: 'EXACT' })).data }
export async function updateProjectAgentNode(projectKey: string, stageKey: string, nodeKey: string, agentProfileVersionId: string | number) { return (await http.put<ProjectAgentConfiguration>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration/nodes/${encodeURIComponent(stageKey)}/${encodeURIComponent(nodeKey)}`, { agentProfileVersionId })).data }
export async function validateProjectAgentConfiguration(projectKey: string) { return (await http.post<ProjectConfigValidation>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration:validate`)).data }
export async function confirmProjectAgentConfiguration(projectKey: string) { return (await http.post<ProjectAgentConfiguration>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration:confirm`)).data }
export async function listReusableProjects(projectKey: string) { return (await http.get<ReusableProject[]>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration/reusable-projects`)).data }
export async function getProjectAgentNode(projectKey: string, stageKey: string, nodeKey: string) { return (await http.get<ProjectAgentNodeDraft>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration/nodes/${encodeURIComponent(stageKey)}/${encodeURIComponent(nodeKey)}`)).data }
export async function saveProjectAgentNodeDraft(projectKey: string, stageKey: string, nodeKey: string, draft: Partial<ProjectAgentNodeDraft>) { return (await http.put<ProjectAgentNodeDraft>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration/nodes/${encodeURIComponent(stageKey)}/${encodeURIComponent(nodeKey)}/draft`, draft)).data }
export async function replaceProjectAgentNodeSource(projectKey: string, stageKey: string, nodeKey: string, agentProfileVersionId: string | number) { return (await http.post<ProjectAgentNodeDraft>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration/nodes/${encodeURIComponent(stageKey)}/${encodeURIComponent(nodeKey)}:replace-source`, { agentProfileVersionId })).data }
export async function reviseProjectAgentConfiguration(projectKey: string) { return (await http.post<ProjectAgentConfiguration>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration:revise`)).data }
function normalizeContexts(raw: ProjectAgentContexts | Array<{ contextKind: string; wikiDocumentId?: string|number|null; wikiRevisionNo?: number|null; feishuDocId?: string|null; feishuDocType?: string|null; title?: string|null }>): ProjectAgentContexts {
  if (!Array.isArray(raw)) return raw
  return { platformWiki: raw.filter(x => x.contextKind === 'PLATFORM_WIKI').map(x => ({ kind: 'PLATFORM_WIKI', id: x.wikiDocumentId ?? '', title: x.title ?? '', revisionNo: x.wikiRevisionNo ?? undefined })), feishu: raw.filter(x => x.contextKind === 'FEISHU').map(x => ({ kind: 'FEISHU', id: x.feishuDocId ?? '', title: x.title ?? '', docType: x.feishuDocType ?? undefined })) }
}
export async function getProjectAgentContexts(projectKey: string) { return normalizeContexts((await http.get<ProjectAgentContexts | Array<{ contextKind: string; wikiDocumentId?: string|number|null; wikiRevisionNo?: number|null; feishuDocId?: string|null; feishuDocType?: string|null; title?: string|null }>>(`/projects/${encodeURIComponent(projectKey)}/agent-configuration/contexts`)).data) }
export async function saveProjectAgentContexts(projectKey: string, contexts: ProjectAgentContexts) { const body = [...contexts.platformWiki.map(x => ({ contextKind: 'PLATFORM_WIKI', wikiDocumentId: x.id, title: x.title })), ...contexts.feishu.map(x => ({ contextKind: 'FEISHU', feishuDocId: String(x.id), feishuDocType: x.docType ?? x.documentType, title: x.title }))]; return normalizeContexts((await http.put(`/projects/${encodeURIComponent(projectKey)}/agent-configuration/contexts`, body)).data) }
